name: Node CI

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
    - name: npm test
      run: npm test
      env:
        CI: true
    - name: collect coverage
      run: npm run test:cov
    - name: sonar-scanner
      uses: Warchant/sonar-scanner-action@v1
      # run only on push to develop/master
      # if: node-version == 12.x && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
      if: matrix.node-version == '12.x'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        options: '-Dsonar.login=${{ secrets.SONAR_TOKEN }}'
