name: Sonarqube

on:
  push:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
    - name: collect coverage
      run: npm run test:cov
    - name: sonar-scanner
      uses: Warchant/sonar-scanner-action@v1
      # run only on push to develop/master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        options: '-Dsonar.login=${{ secrets.SONAR_TOKEN }}'
