name: Sonarqube

on:
  push:
    branches:
    - master
    - develop
    - feature/ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
    - name: collect coverage
      run: npm run test:cov
    - name: setup sonar-scanner
      uses: warchant/setup-sonar-scanner@v1
    - name: run sonar-scanner
      # run only on push to develop/master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}
